apiVersion: v1
kind: Pod
metadata:
  name: test3-root
  namespace: demo
  labels:
    owner: admin
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: test3-root
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "100Mi"
