apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: payments
  name: payments-dev-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "services", "deployments", "replicasets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payments-dev-binding
  namespace: payments
subjects:
- kind: User
  name: payments-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: payments-dev-role
  apiGroup: rbac.authorization.k8s.io
