apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-workload
  namespace: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-app
  template:
    metadata:
      labels:
        app: payments-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: nginx
        image: nginx:1.25.0
        securityContext:
          allowPrivilegeEscalation: false
        # Cố tình KHÔNG khai báo limits/requests ở đây để chứng minh LimitRange hoạt động!
        # Tuy nhiên do Gatekeeper constraint yêu cầu bắt buộc có limits, nên chúng ta 
        # nên khai báo limits để app qua được cổng kiểm duyệt của Gatekeeper.
        # Nếu muốn test LimitRange thì dùng Pod xin RAM to.
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
