apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: demo
spec:
  refreshInterval: 15s # Đồng bộ siêu nhanh để pass bài Lab (<60s)
  secretStoreRef:
    name: fake-provider
    kind: SecretStore
  target:
    name: app-db-secret # Tên K8s Secret sẽ được tạo ra
  data:
    - secretKey: password # Key trong K8s Secret
      remoteRef:
        key: "db-password" # Key tương ứng bên Fake Provider
        version: "v1"
