apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake-provider
  namespace: demo
spec:
  provider:
    fake:
      data:
        - key: "db-password"
          value: "super-secret-v1"
          version: "v1"
